SELECT A.FLAVOR
FROM FIRST_HALF A 
JOIN (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER  -- JULY 는 같은 맛 아이스크림 끼리 합산이 필요함 
FROM JULY 
GROUP BY FLAVOR 
) B 
ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3