-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT t1.CAR_ID, t1.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - t3.DISCOUNT_RATE) * 0.01) AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
     FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE = 'SUV' OR CAR_TYPE = '세단') t1
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE < '2022-11-01' OR START_DATE > '2022-11-30') AND 
(END_DATE < '2022-11-01' OR END_DATE > '2022-11-30')
) t2
ON t1.CAR_ID = t2.CAR_ID 
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE, DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE LIKE '30%')
t3
ON t1.CAR_TYPE = t3.CAR_TYPE
GROUP t1.CAR_ID HAVING t1.CAR_TYPE IN ('세단', 'SUV') AND 
(FEE >= 50000 AND FEE < 2000000)
ORDER BY FEE DESC,t1.CAR_TYPE ASC, t1.CAR_ID DESC