-- https://school.programmers.co.kr/learn/courses/30/lessons/164671

SELECT CONCAT('/home/grep/src/',a.BOARD_ID,'/',FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD a 
JOIN USED_GOODS_FILE b 
ON a.BOARD_ID = b.BOARD_ID
WHERE a.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY b.FILE_ID DESC