-- https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT a.PRODUCT_ID, b.PRODUCT_NAME, 
SUM(b.PRICE * a.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER a 
JOIN (SELECT * FROM FOOD_PRODUCT) b
ON a.PRODUCT_ID = b.PRODUCT_ID 
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY a.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, b.PRODUCT_ID ASC
