-- IFNULL() 함수 사용하기 
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID

-- CASE WHEN 절 사용하기 
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
CASE 
    WHEN FREEZER_YN IS NULL THEN 'N'
    ELSE FREEZER_YN
END AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID

-- IF 절 + SELECT 사용하기 
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID
